name: Push Workflow

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: CMake
        run: cmake -B ./build -DBUILD_TESTS:bool=ON

      - name: Make
        run: cmake --build ./build

      - name: Cache build
        uses: actions/cache@v3
        with:
          path: ./build
          key: ${{ runner.OS }}-build-${{ hashFiles('**/test_mathlib') }}

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get build cache
        uses: actions/cache@v3
        with:
          path: ./build
          key: ${{ runner.OS }}-build-${{ hashFiles('**/test_mathlib') }}
          restore-keys: |
            ${{ runner.OS }}-build-

      - name: Unit Tests
        run: ./build/tests/test_mathlib

  package:
    runs-on: ubuntu-latest
    needs: [ build, test ]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Package .deb
        run: debmake .

      - name: Package .rpm
        run: rpmbuild ./mathlib.spec
