name: Push Workflow

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: CMake
        run: cmake -B ./build -DBUILD_TESTS:bool=ON

      - name: Make
        run: cmake --build ./build

      - name: Cache build
        uses: actions/cache@v3
        with:
          path: ./build
          key: ${{ runner.OS }}-build-${{ hashFiles('**/test_mathlib') }}

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get build cache
        uses: actions/cache@v3
        with:
          path: ./build
          key: ${{ runner.OS }}-build-${{ hashFiles('**/test_mathlib') }}
          restore-keys: |
            ${{ runner.OS }}-build-

      - name: Unit tests
        run: ./build/tests/test_mathlib

  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Get all tags.

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'
          cache-dependency-path: '**/requirements.txt'

      - name: Install docs deps
        run: |
          sudo apt install -y doxygen
          pip install -r ./docs/requirements.txt

      - name: Build docs
        shell: bash -l {0}
        run: |
          sphinx-multiversion -D exhale_args.containmentFolder=\${sourcedir}/api docs .public

      - name: Archive docs
        uses: actions/upload-artifact@v3
        with:
          name: html_docs
          path: ./.public

  package:
    runs-on: ubuntu-latest
    needs: test  # Make sure tests pass before packaging.
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Get build cache
        uses: actions/cache@v3
        with:
          path: ./build
          key: ${{ runner.OS }}-build-${{ hashFiles('**/test_mathlib') }}
          restore-keys: |
            ${{ runner.OS }}-build-

      - name: Package .deb
        run: debmake .

      - name: Package .rpm
        run: rpmbuild ./mathlib.spec
